server:
  host: "localhost"
  port: 8080
database:
  host: "localhost"
  port: 5432
  name: "movie-rental"
  user: "root"
  password: "password"

migrationPaths:
  dev: "internal/db/migration"
  test: "../../internal/db/migration"

